Form validation
security-union/videocall-rs pull request #141
Opened 2023-09-07 02:05 UTC by griffobeid

<img width="1552" alt="image" src="https://github.com/security-union/videocall-rs/assets/12220672/07bab7da-d819-4038-bf6a-855e1bdbb571">

Invalid:
<img width="1552" alt="image" src="https://github.com/security-union/videocall-rs/assets/12220672/f4cadcfa-fea7-4319-935b-7644a4b3d1a6">

Valid:
<img width="1552" alt="image" src="https://github.com/security-union/videocall-rs/assets/12220672/0d47dfd9-60a6-4e7a-9f27-b2f9ea3afe3f">

2023-09-08 01:16 UTC, darioalessandro requested changes
@griffobeid looks good, I found some commented code and a log statement that looks like it was added for testing.

2023-09-08 01:16 UTC, darioalessandro commented on launch_chrome.sh
> +#openssl req -x509 -newkey rsa:2048 -keyout $SCRIPTPATH/actix-api/certs/localhost.key -out $SCRIPTPATH/actix-api/certs/localhost.pem -days 365 -nodes -subj "/CN=127.0.0.1"
commented code

2023-09-08 01:16 UTC, darioalessandro commented on yew-ui/src/components/attendants.rs
> +                    info!("email = {}", email);
do we need this log statements?

2023-09-08 01:16 UTC, darioalessandro commented on yew-ui/src/pages/home.rs
> +                        pattern="^[a-zA-Z0-9_]*$"
nice validation

2023-09-10 12:17 UTC, griffobeid commented on yew-ui/src/components/attendants.rs
> +                    info!("email = {}", email);
Removed this

2023-09-12 13:45 UTC, merged